### ISSUE TITLE
Support Magisk?

### ISSUE THREAD

**Issue by Louissenny** [apsun/NekoSMS#57] opened 2019-03-03 17:00 UTC
It's still not easy for Android P devices to install Xposed but Magisk works just fine, so would you develop a version which can be used on Magisk?

**Comment by apsun** [comment] 2019-03-03 17:05
Dupe of #34. Translated: Magisk lets you replace files, Xposed lets you inject code into existing files. Creating a version for Magisk would basically require compiling a custom system file for every Android device in existence, which is not feasible unfortunately.

**Closed by apsun** 2019-03-03 17:05 UTC
